spring:
  application:
    name: kafka-publisher-service

  datasource:
    url: jdbc:h2:tcp://localhost:9093/mem:fileprocessordb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

kafka:
  topic:
    transaction-events: transaction-events

outbox:
  polling:
    interval: 5000  # 5 seconds

logging:
  level:
    com.example.kafka: DEBUG
    org.springframework.kafka: INFO

